# Generated by Django 5.1.2 on 2024-11-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_course_courseimage_course_techs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_categories',
            name='Course_description',
            field=models.TextField(max_length=500),
        ),
    ]
