# Generated by Django 5.1.2 on 2024-11-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_alter_course_categories_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseImage',
        ),
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(null=True, upload_to='course_images/'),
        ),
    ]
