# Generated by Django 5.1.2 on 2024-11-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_remove_course_courseimage_course_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_image',
        ),
        migrations.AddField(
            model_name='course',
            name='courseImage',
            field=models.ImageField(null=True, upload_to='course_imgs/'),
        ),
    ]
