# Generated by Django 5.1.2 on 2024-11-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_remove_course_course_image_course_courseimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Teacher',
        ),
    ]
